# Generated by Django 6.1.1 on 2026-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='cartas/'),
        ),
    ]
